export type Country = {
  code: string;
  name: string;
  flag: string;
  currency: string;
  phoneCode: string;
  cities: string[];
};

/**
 * Extrait dynamiquement le code ISO 2 lettres à partir de l'emoji drapeau Unicode (ex: '🇨🇮' -> 'CI', '🇧🇫' -> 'BF')
 */
export function flagToIso(flag: string): string {
  if (!flag) return '';
  const codePoints = Array.from(flag).map((ch) => ch.codePointAt(0) || 0);
  if (codePoints.length >= 2 && codePoints[0] >= 0x1f1e6 && codePoints[0] <= 0x1f1ff) {
    const char1 = String.fromCharCode(codePoints[0] - 0x1f1e6 + 65);
    const char2 = String.fromCharCode(codePoints[1] - 0x1f1e6 + 65);
    return `${char1}${char2}`;
  }
  return '';
}

/**
 * Normalise dynamiquement n'importe quel identifiant pays (ISO, indicatif, nom, code) en utilisant 100% de la constante PAYS.
 */
export function normalizeCountry(country?: string): string | undefined {
  if (!country || typeof country !== 'string') return undefined;
  const trimmed = country.trim();
  if (!trimmed) return undefined;
  const lower = trimmed.toLowerCase();
  const upper = trimmed.toUpperCase();
  const cleanPhone = lower.startsWith('+') ? lower : `+${lower}`;

  const found = PAYS.find((c) => {
    const iso = flagToIso(c.flag);
    const nameNorm = c.name.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();
    const inputNorm = lower.normalize('NFD').replace(/[\u0300-\u036f]/g, '');

    return (
      c.code.toLowerCase() === lower ||
      (iso && iso.toUpperCase() === upper) ||
      c.phoneCode.toLowerCase() === lower ||
      c.phoneCode.toLowerCase() === cleanPhone ||
      c.phoneCode.replace('+', '').toLowerCase() === lower ||
      c.name.toLowerCase() === lower ||
      nameNorm === inputNorm
    );
  });

  if (found) {
    return found.code;
  }

  return trimmed;
}

/**
 * Génère des conditions d'égalité pour MongoDB couvrant toutes les variantes du pays recherché.
 */
export function buildCountryQueryFilter(country?: string): any[] {
  const norm = normalizeCountry(country);
  const raw = country ? country.trim() : '';
  const set = new Set<string>();

  if (norm) {
    set.add(norm);
    set.add(norm.toUpperCase());
    set.add(norm.toLowerCase());
    
    const found = PAYS.find((c) => c.code === norm);
    if (found) {
      set.add(found.code);
      set.add(found.phoneCode);
      set.add(found.phoneCode.replace('+', ''));
      const iso = flagToIso(found.flag);
      if (iso) {
        set.add(iso);
        set.add(iso.toLowerCase());
      }
    }
  }

  if (raw) {
    set.add(raw);
    set.add(raw.toUpperCase());
    set.add(raw.toLowerCase());
  }

  const countryConditions: any[] = Array.from(set).map((c) => ({ country: c }));
  countryConditions.push({ country: { $exists: false } });
  countryConditions.push({ country: null });
  countryConditions.push({ country: '' });

  return countryConditions;
}

export const PAYS: Country[] = [
  {
    code: 'benin',
    name: 'Bénin',
    flag: '🇧🇯',
    currency: 'XOF',
    phoneCode: '+229',
    cities: [
      'Cotonou',
      'Porto-Novo',
      'Parakou',
      'Djougou',
      'Bohicon',
      'Kandi',
      'Lokossa',
      'Abomey-Calavi',
      'Natitingou',
      'Save',
      'Ouidah',
      'Malanville',
      'Cové',
      'Tanguiéta',
      'Pobè',
      'Savalou',
      'Sakété',
      'Bassila',
      'Dassa-Zoumè',
      'Tchaourou',
      'Dogbo-Tota',
      'Aplahoué',
      'Allada',
      'Sèmè-Kpodji',
      'Nikki',
      'Bembèrèkè',
      'Beterou',
      'Grand-Popo',
      'Kétou',
      'Athiémé',
    ],
  },
  {
    code: 'burkina_faso',
    name: 'Burkina Faso',
    flag: '🇧🇫',
    currency: 'XOF',
    phoneCode: '+226',
    cities: [
      'Ouagadougou',
      'Bobo-Dioulasso',
      'Koudougou',
      'Banfora',
      'Dédougou',
      'Ouahigouya',
      "Fada N'Gourma",
      'Tenkodogo',
      'Kaya',
      'Houndé',
      'Dori',
      'Réo',
      'Manga',
      'Ziniaré',
      'Garango',
      'Koupéla',
      'Kombissiri',
      'Yako',
      'Ouargaye',
      'Diapaga',
      'Nouna',
      'Gourcy',
      'Leo',
      'Solenzo',
      'Pô',
      'Dano',
      'Tougan',
      'Boulsa',
      'Léo',
      'Bopolu',
    ],
  },
  {
    code: 'cap_vert',
    name: 'Cap-Vert',
    flag: '🇨🇻',
    currency: 'CVE',
    phoneCode: '+238',
    cities: [
      'Praia',
      'Mindelo',
      'Santa Maria',
      'Cova Figueira',
      'Tarrafal',
      'Assomada',
      'Pedra Badejo',
      'Porto Novo',
      'Vila do Maio',
      'Espargos',
      'Vila da Ribeira Brava',
      'Cidade Velha',
      'Calheta de São Miguel',
      'Ponta do Sol',
      'São Filipe',
      'Cidade Baixa',
      'Sal Rei',
      'São Domingos',
      'Cachoeira',
      'São Miguel',
      'Picos',
      'João Teves',
      'São Lourenço dos Órgãos',
      'Tarrafal de São Nicolau',
      'Mosteiros',
      'Ribeira Grande',
      'Lomba',
      'Paul',
      'Porto Ingles',
    ],
  },
  {
    code: 'cote_d_ivoire',
    name: "Côte d'Ivoire",
    flag: '🇨🇮',
    currency: 'XOF',
    phoneCode: '+225',
    cities: [
      'Abidjan',
      'Yamoussoukro',
      'Bouaké',
      'Daloa',
      'San-Pédro',
      'Korhogo',
      'Man',
      'Divo',
      'Gagnoa',
      'Anyama',
      'Abobo',
      'Séguéla',
      'Oumé',
      'Tiassalé',
      'Dabou',
      'Toumodi',
      'Bondoukou',
      'Guiglo',
      'Bongouanou',
      'Issia',
      'Sassandra',
      'Bangolo',
      'Akoupé',
      'Zuénoula',
      'Grand-Bassam',
      'Abengourou',
      'Agnibilékrou',
      'Dimbokro',
      'Adzopé',
      'Aboisso',
      'Katiola',
      'Tengrela',
      'Duékoué',
      'Ferkessedougou',
      'Lakota',
      'Sinfra',
      'Vavoua',
      'Touba',
      'Kouto',
      'Bouna',
      'Séguélon',
      'Tanda',
      'Agboville',
      'Tabou',
      'Guibéroua',
      'Odienné',
      'Boundiali',
      'Daoukro',
      'Biankouma',
    ],
  },
  {
    code: 'gambie',
    name: 'Gambie',
    flag: '🇬🇲',
    currency: 'GMD',
    phoneCode: '+220',
    cities: [
      'Banjul',
      'Serekunda',
      'Brikama',
      'Bakau',
      'Farafenni',
      'Lamin',
      'Kanifing',
      'Kololi',
      'Basse Santa Su',
      'Bakoteh',
      'Bansang',
      'Barra',
      'Brufut',
      'Essau',
      'Gunjur',
      'Kuntaur',
      'Manjai',
      'Sabieh',
      'Sukuta',
      'Tanji',
      'Janjanbureh',
      'Kerewan',
      'Kudang',
      'Kwinella',
      'Newtown',
      'Old Jeshwang',
      'Old Yundum',
      'Saba',
      'Soma',
      'Sotuma Sere',
      'Wassu',
      'Yundum',
      'Kotu',
      'Jambur',
      'Kanifing',
      'Bakoteh',
      'Kololi',
    ],
  },
  {
    code: 'ghana',
    name: 'Ghana',
    flag: '🇬🇭',
    currency: 'GHS',
    phoneCode: '+233',
    cities: [
      'Accra',
      'Kumasi',
      'Tamale',
      'Takoradi',
      'Sekondi-Takoradi',
      'Cape Coast',
      'Sunyani',
      'Ho',
      'Bolgatanga',
      'Wa',
      'Techiman',
      'Koforidua',
      'Nungua',
      'Tema',
      'Ashiaman',
      'Dome',
      'Teshie',
      'Sekondi',
      'Obuasi',
      'Madina',
      'Kintampo',
      'Adenta',
      'Nsawam',
      'Hohoe',
      'Akim Oda',
      'Tarkwa',
      'Akropong',
      'Bawku',
      'Navrongo',
      'Keta',
      'Berekum',
      'Swedru',
      'Nkawkaw',
      'Dunkwa-on-Offin',
      'Axim',
      'Kibi',
      'Shama Junction',
      'Mampong',
      'Anloga',
      'Bogoso',
      'Aburi',
      'Apam',
      'Suhum',
      'Elmina',
      'Salaga',
      'Bibiani',
    ],
  },
  {
    code: 'guinee',
    name: 'Guinée',
    flag: '🇬🇳',
    currency: 'GNF',
    phoneCode: '+224',
    cities: [
      'Conakry',
      'Nzérékoré',
      'Kankan',
      'Kindia',
      'Labé',
      'Boffa',
      'Macenta',
      'Kissidougou',
      'Gueckedou',
      'Coyah',
      'Kamsar',
      'Fria',
      'Siguiri',
      'Pita',
      'Dabola',
      'Mamou',
      'Télimélé',
      'Kouroussa',
      'Boké',
      'Faranah',
      'Tougué',
      'Dubréka',
      'Dinguiraye',
      'Forécariah',
      'Koubia',
      'Mandiana',
      'Dalaba',
      'Guékédou',
      'Kérouané',
      'Yomou',
      'Gaoual',
      'Lélouma',
      'Koundara',
      'Mali',
      'Beyla',
    ],
  },
  {
    code: 'guinee_bissau',
    name: 'Guinée-Bissau',
    flag: '🇬🇼',
    currency: 'XOF',
    phoneCode: '+245',
    cities: [
      'Bissau',
      'Bafatá',
      'Gabú',
      'Bolama',
      'Cacheu',
      'Canchungo',
      'Buba',
      'Mansôa',
      'Quinhamel',
      'Bissorã',
      'Farim',
      'Fulacunda',
      'Catió',
      'Quebo',
      'Cacine',
      'Bubaque',
    ],
  },
  {
    code: 'liberia',
    name: 'Libéria',
    flag: '🇱🇷',
    currency: 'LRD',
    phoneCode: '+231',
    cities: [
      'Monrovia',
      'Gbarnga',
      'Bensonville',
      'Harper',
      'Zwedru',
      'Buchanan',
      'Ganta',
      'Kakata',
      'Voinjama',
      'Barclayville',
      'Sanniquellie',
      'Bopolu',
      'Zorzor',
      'Kasongo',
      'Pleebo',
      'Fish Town',
      'Robertsport',
      'Gbarpolu City',
      'Paynesville',
      'Vahun',
      'Tubmanburg',
      'River Gee',
    ],
  },
  {
    code: 'mali',
    name: 'Mali',
    flag: '🇲🇱',
    currency: 'XOF',
    phoneCode: '+223',
    cities: [
      'Bamako',
      'Ségou',
      'Mopti',
      'Timbuktu',
      'Kayes',
      'Sikasso',
      'Gao',
      'Koutiala',
      'Koulikoro',
      'Kati',
      'Markala',
      'Djénné',
      'Nioro du Sahel',
      'Kolokani',
      'San',
      'Kangaba',
      'Bougouni',
      'Tombouctou',
      'Goundam',
      'Bafoulabé',
      'Kita',
      'Yorosso',
      'Banamba',
      'Kidal',
      'Tessalit',
      'Ténenkou',
      'Koro',
      'Bla',
      'Youwarou',
      'Ménaka',
      'Ké-Macina',
    ],
  },
  {
    code: 'mauritanie',
    name: 'Mauritanie',
    flag: '🇲🇷',
    currency: 'MRU',
    phoneCode: '+222',
    cities: [
      'Nouakchott',
      'Nouadhibou',
      'Kiffa',
      'Rosso',
      'Kaédi',
      'Zouérat',
      'Atar',
      'Tidjikdja',
      'Sélibaby',
      'Néma',
      'Aioun',
      'Akjoujt',
      'Aleg',
      'Bogué',
      'Guérou',
      'Boutilimit',
      'Maghama',
      'Aïoun El Atrouss',
      'Bababé',
      'Boghé',
      'Oualata',
      'Timbedra',
      'Amourj',
      'Mederdra',
      'Benne',
      "R'Kiz",
      'Bou Lanouar',
      'Louga',
      'Taboukourt',
      'Dar Naim',
      'Lemden',
      'Tachott',
      'Dawar Al Sawalih',
      'Talloul',
      'Daïra',
      'Toujounine',
      'Inal',
      'Mékhé',
      'Barkéol',
      'Djiguenni',
      'Aoujeft',
      'Ouad Naga',
      'Magta-Lahjar',
      'Hassi Cheggar',
      'Tékane',
    ],
  },
  {
    code: 'niger',
    name: 'Niger',
    flag: '🇳🇪',
    currency: 'XOF',
    phoneCode: '+227',
    cities: [
      'Niamey',
      'Zinder',
      'Maradi',
      'Agadez',
      'Tahoua',
      'Dosso',
      'Diffa',
      'Tillabéri',
      'Madaoua',
      'Mirriah',
      'Arlit',
      "Birni-N'Konni",
      'Gaya',
      'Dogondoutchi',
      'Tessaoua',
      'Mayahi',
      'Téra',
      'Goure',
      'Dakoro',
      'Matameye',
      'Maïné-Soroa',
      'Magaria',
      'Bouza',
      'Tanout',
      'Nguigmi',
      'Illela',
      'Keita',
      'Aguie',
      'Ayorou',
      'Tibiri',
      'Kollo',
      'Madarounfa',
      'Say',
      'Malbaza',
      'Djado',
      'Filingué',
      'Bilma',
      'Guidimouni',
    ],
  },
  {
    code: 'nigeria',
    name: 'Nigeria',
    flag: '🇳🇬',
    currency: 'NGN',
    phoneCode: '+234',
    cities: [
      'Lagos',
      'Kano',
      'Ibadan',
      'Kaduna',
      'Port Harcourt',
      'Benin City',
      'Maiduguri',
      'Zaria',
      'Aba',
      'Jos',
      'Ilorin',
      'Oyo',
      'Enugu',
      'Abeokuta',
      'Abuja',
      'Sokoto',
      'Onitsha',
      'Warri',
      'Okene',
      'Calabar',
      'Katsina',
      'Akure',
      'Ado-Ekiti',
      'Kumariya',
      'Bauchi',
      'Ebute Ikorodu',
      'Makurdi',
      'Minna',
      'Effon Alaiye',
      'Ilesha',
      'Owo',
      'Umuahia',
      'Ondo',
      'Damaturu',
      'Ikot Ekpene',
      'Iwo',
      'Gombe',
      'Jimeta',
      'Gusau',
      'Mubi',
      'Funtua',
      'Biu',
      'Nsukka',
      'Nguru',
      'Hadejia',
      'Ijebu Ode',
      'Ugep',
      'Ejigbo',
      'Sapele',
      'Kontagora',
      'Ife',
      'Ijero-Ekiti',
      'Wukari',
      'Wudil',
      'Lafiagi',
      'Bida',
      'Okrika',
      'Amaigbo',
      'Bama',
      'Ilobu',
      'Jalingo',
    ],
  },
  {
    code: 'senegal',
    name: 'Sénégal',
    flag: '🇸🇳',
    currency: 'XOF',
    phoneCode: '+221',
    cities: [
      'Dakar',
      'Thiès',
      'Grand Dakar',
      'Ziguinchor',
      'Touba',
      'Rufisque',
      'Kaolack',
      'Mbour',
      'Saint-Louis',
      'Diourbel',
      'Louga',
      'Fatick',
      'Kolda',
      'Tambacounda',
      'Médina',
      'Dakar Plateau',
      'Sédhiou',
      'Joal-Fadiouth',
      'Mbake',
      'Podor',
      'Pikine',
      'Tivaouane',
      'Kédougou',
      'Vélingara',
      'Kayar',
      'Kébémer',
      'Nioro du Rip',
      'Pourham',
      'Guédiawaye',
      'Médina Gounass',
      'Koungheul',
      'Darou Mousty',
      'Sokone',
      'Ourossogui',
      'Pout',
      'Ngaye Méckhe',
      'Kaffrine',
      'Dagana',
    ],
  },
  {
    code: 'sierra_leone',
    name: 'Sierra Leone',
    flag: '🇸🇱',
    currency: 'SLL',
    phoneCode: '+232',
    cities: [
      'Freetown',
      'Bo',
      'Kenema',
      'Koidu',
      'Makeni',
      'Lunsar',
      'Port Loko',
      'Kabala',
      'Pujehun',
      'Kailahun',
      'Magburaka',
      'Bonthe',
      'Masiaka',
      'Kambia',
      'Marampa',
      'Waterloo',
      'Kamakwie',
      'Koribondo',
      'Lungi',
      'Karene',
      'Yengema',
      'Rokupr',
      'Goderich',
      'Rokel',
      'Gberia Fotombu',
      'Baoma',
      'Yonibana',
      'Lunga',
      'Shenge',
      'Zimmi',
      'Pandebu-Tokpombu',
      'Sumbuya',
      'Bumpe',
      'Baiima',
      'Falaba',
      'Matru',
      'Segbwema',
      'Yele',
      'Kawama',
      'Masimera',
      'Tongo',
      'Pendembu',
      'Potoru',
      'Mattru',
    ],
  },
  {
    code: 'togo',
    name: 'Togo',
    flag: '🇹🇬',
    currency: 'XOF',
    phoneCode: '+228',
    cities: [
      'Lomé',
      'Sokodé',
      'Kara',
      'Atakpamé',
      'Palimé',
      'Bassar',
      'Tsevie',
      'Aného',
      'Sansanné-Mango',
      'Dapaong',
      'Tchamba',
      'Niamtougou',
      'Bafilo',
      'Sotouboua',
      'Vogan',
      'Badou',
      'Amlamé',
      'Kandé',
      'Notsé',
      'Tchaoudjo',
      'Notse',
      'Tabligbo',
      'Tandjouaré',
      'Kpagouda',
      'Mango',
    ],
  },
  {
    code: 'tunisie',
    name: 'Tunisie',
    flag: '🇹🇳',
    currency: 'TND',
    phoneCode: '+216',
    cities: [
      'Tunis',
      'Sfax',
      'Sousse',
      'Midoun',
      'Kairouan',
      'Bizerte',
      'Gabès',
      'Aryanah',
      'Gafsa',
      'El Mourouj',
      'Kasserine',
      'Monastir',
      'Nabeul',
      'Tataouine',
      'Béja',
      'La Goulette',
      'Sidi Bouzid',
      'Ben Arous',
      'Kram',
      'La Marsa',
      'La Manouba',
      'Hammam Sousse',
      'Mahdia',
      'Sidi Hassine',
      'Jendouba',
      'Zarzis',
      'Grombalia',
      'Moknine',
      'Hammam Lif',
      'Douane',
    ],
  },
  {
    code: 'zambie',
    name: 'Zambie',
    flag: '🇿🇲',
    currency: 'ZMW',
    phoneCode: '+260',
    cities: [
      'Lusaka',
      'Kitwe',
      'Ndola',
      'Kabwe',
      'Chingola',
      'Mufulira',
      'Luanshya',
      'Livingstone',
      'Kasama',
      'Chipata',
      'Kalulushi',
      'Mazabuka',
      'Chililabombwe',
      'Mongu',
      'Kafue',
      'Chambishi',
      'Mpika',
      'Nchelenge',
      'Kapiri Mposhi',
      'Kalomo',
      'Kansanshi',
      'Chinsali',
      'Mansa',
      'Kawambwa',
      'Mbala',
      'Petauke',
      'Samfya',
      'Choma',
      'Monze',
      'Solwezi',
      'Chirundu',
      'Kaputa',
      'Kaoma',
      'Mwinilunga',
      'Luwingu',
      'Serenje',
      'Nakonde',
      'Sesheke',
      'Mumbwa',
      'Isoka',
      'Mkushi',
      'Maamba',
      'Lundazi',
      'Namwala',
    ],
  },
  {
    code: 'zimbabwe',
    name: 'Zimbabwe',
    flag: '🇿🇼',
    currency: 'ZWL',
    phoneCode: '+263',
    cities: [
      'Harare',
      'Bulawayo',
      'Chitungwiza',
      'Mutare',
      'Gweru',
      'Epworth',
      'Kwekwe',
      'Kadoma',
      'Masvingo',
      'Chinhoyi',
      'Marondera',
      'Norton',
      'Chegutu',
      'Bindura',
      'Zvishavane',
      'Victoria Falls',
      'Hwange',
      'Redcliff',
      'Ruwa',
      'Beitbridge',
      'Chiredzi',
      'Gokwe',
      'Shurugwi',
      'Gwanda',
      'Shamva',
      'Chivhu',
      'Mazowe',
      'Mashava',
      'Banket',
      'Mutoko',
      'Murewa',
      'Glendale',
      'Greendale',
      'Mbare',
      'Mufakose',
      'Budiriro',
      'Dzivarasekwa',
      'Kuwadzana',
      'Glen View',
      'Highfields',
      'Warren Park',
      'Waterfalls',
      'Mount Pleasant',
      'Avondale',
      'Borrowdale',
      'Marlborough',
    ],
  },
  {
    code: 'algerie',
    name: 'Algérie',
    flag: '🇩🇿',
    currency: 'DZD',
    phoneCode: '+213',
    cities: [
      'Alger',
      'Oran',
      'Constantine',
      'Annaba',
      'Batna',
      'Blida',
      'Setif',
      'Chlef',
      'Djelfa',
      'Sidi Bel Abbes',
      'Biskra',
      'Tebessa',
      'El Oued',
      'Skikda',
      'Tiaret',
      'Bejaia',
      'Tlemcen',
      'Ouargla',
      'Ghardaia',
      'Mostaganem',
      'El Eulma',
      'Saida',
      'Guelma',
      'Bordj Bou Arreridj',
      'Bechar',
      'Tamanrasset',
      'Adrar',
      'Tindouf',
      'Illizi',
    ],
  },
  {
    code: 'angola',
    name: 'Angola',
    flag: '🇦🇴',
    currency: 'AOA',
    phoneCode: '+244',
    cities: [
      'Luanda',
      'Huambo',
      'Lobito',
      'Benguela',
      'Kuito',
      'Lubango',
      'Malanje',
      'Namibe',
      'Soyo',
      'Cabinda',
      'Uige',
      'Tombua',
      'Sumbe',
      'Caxito',
      'Lwena',
      'Menongue',
      'Lucapa',
      'Dundo',
      'Ndalatando',
      'Ondjiva',
      'Mbanza Kongo',
      'Saurimo',
      'Luena',
      'Caconda',
      'Caculo Cabaça',
      'Caluquembe',
      'Cangandala',
      'Capenda Camulemba',
      'Catabola',
    ],
  },
  {
    code: 'cameroun',
    name: 'Cameroun',
    flag: '🇨🇲',
    currency: 'XAF',
    phoneCode: '+237',
    cities: [
      'Douala',
      'Yaoundé',
      'Garoua',
      'Bamenda',
      'Maroua',
      'Bafoussam',
      'Ngaoundéré',
      'Bertoua',
      'Kumba',
      'Kribi',
      'Ebolowa',
      'Kousséri',
      'Foumban',
      'Edea',
      'Buea',
      'Bafang',
      'Mbalmayo',
      'Bangangte',
      'Limbe',
      'Kribi',
      'Kribi',
      'Kribi',
      'Kribi',
      'Kribi',
      'Kribi',
      'Kribi',
      'Kribi',
    ],
  },
  {
    code: 'republique_centrafricaine',
    name: 'République centrafricaine',
    flag: '🇨🇫',
    currency: 'XAF',
    phoneCode: '+236',
    cities: [
      'Bangui',
      'Bimbo',
      'Mbaiki',
      'Berbérati',
      'Carnot',
      'Bambari',
      'Bouar',
      'Bossangoa',
      'Bria',
      'Bangassou',
      'Nola',
      'Kaga-Bandoro',
      'Sibut',
      'Mobaye',
      'Obo',
      'Birao',
      'Ndele',
      'Kembe',
      'Zemio',
      'Bakouma',
      'Rafaï',
      'Gambo',
      'Ouadda',
      'Bakouma',
      'Bakouma',
      'Bakouma',
    ],
  },
  {
    code: 'tchad',
    name: 'Tchad',
    flag: '🇹🇩',
    currency: 'XAF',
    phoneCode: '+235',
    cities: [
      "N'Djamena",
      'Moundou',
      'Sarh',
      'Abéché',
      'Kelo',
      'Koumra',
      'Pala',
      'Am Timan',
      'Bongor',
      'Mongo',
      'Doba',
      'Ati',
      'Lai',
      'Oum Hadjer',
      'Bitkine',
      'Mao',
      'Massaguet',
      'Dourbali',
      'Kyabe',
      'Gounou Gaya',
      'Guelendeng',
      'Beinamar',
      'Ngama',
      'Adre',
      'Goz Beida',
      'Bokoro',
    ],
  },
  {
    code: 'comores',
    name: 'Comores',
    flag: '🇰🇲',
    currency: 'KMF',
    phoneCode: '+269',
    cities: [
      'Moroni',
      'Mutsamudu',
      'Fomboni',
      'Domoni',
      'Tsimbeo',
      'Adda-Douéni',
      'Mirontsi',
      'Ouani',
      'Moya',
      'Mbeni',
      'Mitsamiouli',
      'Barakani',
      'Chandra',
      'Mtsangamouji',
      'Oungoni',
      'Mitsoudje',
      'Koni-Djodjo',
      'Moya',
      'Hahaya',
      'Bambao',
      'Hambou',
      'Hantsambou',
      'Ouellah',
      'Bambao',
    ],
  },
  {
    code: 'congo',
    name: 'Congo',
    flag: '🇨🇬',
    currency: 'XAF',
    phoneCode: '+242',
    cities: [
      'Brazzaville',
      'Pointe-Noire',
      'Dolisie',
      'Nkayi',
      'Impfondo',
      'Ouesso',
      'Madingou',
      'Gamboma',
      'Owando',
      'Loandjili',
      'Mossendjo',
      'Kayes',
      'Djambala',
      'Ewo',
      'Sibiti',
      'Makoua',
      'Gamboma',
      'Boko',
      'Madingou',
      'Kinkala',
      'Mossaka',
      'Lekana',
      'Abala',
      'Etoumbi',
    ],
  },
  {
    code: 'republique_democratique_congo',
    name: 'République démocratique du Congo',
    flag: '🇨🇩',
    currency: 'CDF',
    phoneCode: '+243',
    cities: [
      'Kinshasa',
      'Lubumbashi',
      'Mbuji-Mayi',
      'Kananga',
      'Kisangani',
      'Bukavu',
      'Kolwezi',
      'Likasi',
      'Goma',
      'Tshikapa',
      'Kikwit',
      'Uvira',
      'Bunia',
      'Mbandaka',
      'Matadi',
      'Kindu',
      'Kalemie',
      'Kamina',
      'Butembo',
      'Beni',
      'Mweka',
      'Kabinda',
      'Kisantu',
      'Boma',
      'Kipushi',
    ],
  },
  {
    code: 'djibouti',
    name: 'Djibouti',
    flag: '🇩🇯',
    currency: 'DJF',
    phoneCode: '+253',
    cities: [
      'Djibouti',
      'Ali Sabieh',
      'Tadjourah',
      'Obock',
      'Dikhil',
      'Arta',
      'Holhol',
      'Dorra',
      'Galafi',
      'Loyada',
      'Anse Boileau',
      'Anse Royale',
      'Beau Vallon',
      'Cascade',
      'Glacis',
      'Grand Anse',
      'La Digue',
      'La Rivière Anglaise',
      'Mont Buxton',
      'Mont Fleuri',
      'Plaisance',
    ],
  },
  {
    code: 'egypte',
    name: 'Égypte',
    flag: '🇪🇬',
    currency: 'EGP',
    phoneCode: '+20',
    cities: [
      'Le Caire',
      'Alexandrie',
      'Gizeh',
      'Shubra El Kheima',
      'Port-Saïd',
      'Suez',
      'Louxor',
      'Mansourah',
      'El-Mahalla El-Kubra',
      'Assiout',
      'Tanta',
      'Fayoum',
      'Zagazig',
      'Assouan',
      'Ismaïlia',
      'Kafr El Sheikh',
      'Aswan',
      'Damanhour',
      'El-Minya',
      'Beni Suef',
      'Qena',
      'Sohag',
      'Hurghada',
      '6th of October City',
      'Sharm El Sheikh',
      'New Cairo',
      'El Obour',
    ],
  },
  {
    code: 'erythree',
    name: 'Érythrée',
    flag: '🇪🇷',
    currency: 'ERN',
    phoneCode: '+291',
    cities: [
      'Asmara',
      'Keren',
      'Massawa',
      'Assab',
      'Mendefera',
      'Dekemhare',
      'Akordat',
      'Barentu',
      'Teseney',
      'Adi Keyh',
      'Adi Quala',
      'Dekemhare',
      'Mendefera',
      'Segheneyti',
      'Adi Quala',
      'Adi Quala',
      'Adi Quala',
      'Adi Quala',
      'Adi Quala',
      'Adi Quala',
      'Adi Quala',
      'Adi Quala',
    ],
  },
  {
    code: 'ethiopie',
    name: 'Éthiopie',
    flag: '🇪🇹',
    currency: 'ETB',
    phoneCode: '+251',
    cities: [
      'Addis-Abeba',
      'Dire Dawa',
      'Mekele',
      'Gondar',
      'Adama',
      'Jimma',
      'Dessie',
      'Bahir Dar',
      'Jijiga',
      'Shashamane',
      'Bishoftu',
      'Arba Minch',
      'Hosaena',
      'Harar',
      'Dilla',
      'Nekemte',
      'Debre Birhan',
      'Asella',
      'Hawassa',
      'Bale Robe',
      'Debre Markos',
      'Kombolcha',
      'Debre Tabor',
    ],
  },
  {
    code: 'gabon',
    name: 'Gabon',
    flag: '🇬🇦',
    currency: 'XAF',
    phoneCode: '+241',
    cities: [
      'Libreville',
      'Port-Gentil',
      'Franceville',
      'Oyem',
      'Moanda',
      'Mouila',
      'Lambarene',
      'Tchibanga',
      'Koulamoutou',
      'Makokou',
      'Bitam',
      'Tsogni',
      'Gamba',
      'Mounana',
      'Lalara',
      'Minvoul',
      'Medouneu',
      'Omboue',
      'Ndjole',
      'Lastoursville',
      'Okondja',
      'Booue',
      'Fougamou',
    ],
  },
  {
    code: 'kenya',
    name: 'Kenya',
    flag: '🇰🇪',
    currency: 'KES',
    phoneCode: '+254',
    cities: [
      'Nairobi',
      'Mombasa',
      'Kisumu',
      'Nakuru',
      'Eldoret',
      'Thika',
      'Malindi',
      'Kitale',
      'Kakamega',
      'Nyeri',
      'Machakos',
      'Embu',
      'Kericho',
      'Kisii',
      'Garissa',
      'Wajir',
      'Lamu',
      'Bungoma',
      'Busia',
      'Homa Bay',
      'Kajiado',
      'Kilifi',
      'Kirinyaga',
      'Kitui',
      'Kwale',
      'Laikipia',
      'Lamu',
      'Mandera',
      'Marsabit',
      'Meru',
    ],
  },
  {
    code: 'libye',
    name: 'Libye',
    flag: '🇱🇾',
    currency: 'LYD',
    phoneCode: '+218',
    cities: [
      'Tripoli',
      'Benghazi',
      'Misrata',
      'Tarhuna',
      'El Khums',
      'Zawiya',
      'Ajdabiya',
      'Tobrouk',
      'Sabha',
      'Derna',
      'Tobruk',
      'Al Bayda',
      'Zliten',
      'Tajura',
      'Murzuq',
      'Ghat',
      'Jalu',
      'Ubari',
      'Ghadames',
      'Nalut',
      'Yafran',
      'Zintan',
      'Al Marj',
      'Al Qubbah',
      'Al Abyar',
    ],
  },
  {
    code: 'madagascar',
    name: 'Madagascar',
    flag: '🇲🇬',
    currency: 'MGA',
    phoneCode: '+261',
    cities: [
      'Antananarivo',
      'Toamasina',
      'Antsirabe',
      'Fianarantsoa',
      'Mahajanga',
      'Toliara',
      'Antsiranana',
      'Antanifotsy',
      'Ambalavao',
      'Ambanja',
      'Ambatondrazaka',
      'Ambilobe',
      'Andoany',
      'Antalaha',
      'Antanambao Manampontsy',
      'Antsohihy',
      'Brickaville',
      'Farafangana',
      'Fenoarivo Atsinanana',
      'Fenoarivo Be',
      'Fort Dauphin',
      'Hell-Ville',
      'Ihosy',
      'Maevatanana',
    ],
  },
  {
    code: 'malawi',
    name: 'Malawi',
    flag: '🇲🇼',
    currency: 'MWK',
    phoneCode: '+265',
    cities: [
      'Lilongwe',
      'Blantyre',
      'Mzuzu',
      'Zomba',
      'Kasungu',
      'Mangochi',
      'Karonga',
      'Salima',
      'Nkhotakota',
      'Liwonde',
      'Nsanje',
      'Rumphi',
      'Mzimba',
      'Balaka',
      'Mchinji',
      'Dowa',
      'Ntchisi',
      'Dedza',
      'Ntcheu',
      'Lilongwe',
      'Lilongwe',
      'Lilongwe',
      'Lilongwe',
      'Lilongwe',
    ],
  },
  {
    code: 'maurice',
    name: 'Maurice',
    flag: '🇲🇺',
    currency: 'MUR',
    phoneCode: '+230',
    cities: [
      'Port Louis',
      'Beau Bassin-Rose Hill',
      'Vacoas-Phoenix',
      'Curepipe',
      'Quatre Bornes',
      'Triolet',
      'Goodlands',
      'Centre de Flacq',
      'Bel Air Rivière Sèche',
      'Mahébourg',
      'Saint Pierre',
      'Bambous',
      'Cascavelle',
      'Grand Baie',
      'Grand Gaube',
      'Grande Rivière Noire',
      "L'Escalier",
      'Moka',
      'Pamplemousses',
      'Plaine Magnien',
      'Quatre Soeurs',
      'Rivière du Rempart',
    ],
  },
  {
    code: 'maroc',
    name: 'Maroc',
    flag: '🇲🇦',
    currency: 'MAD',
    phoneCode: '+212',
    cities: [
      'Casablanca',
      'Rabat',
      'Fès',
      'Marrakech',
      'Agadir',
      'Tanger',
      'Meknès',
      'Oujda',
      'Kénitra',
      'Tétouan',
      'Safi',
      'El Jadida',
      'Beni Mellal',
      'Nador',
      'Taza',
      'Settat',
      'Larache',
      'Ksar El Kebir',
      'Témara',
      'Mohammedia',
      'Khouribga',
      'Béni Mellal',
      'Taourirt',
      'Errachidia',
      'Taroudant',
      'Sefrou',
      'Ouarzazate',
      'Ifrane',
      'Azrou',
      'Midelt',
    ],
  },
  {
    code: 'mozambique',
    name: 'Mozambique',
    flag: '🇲🇿',
    currency: 'MZN',
    phoneCode: '+258',
    cities: [
      'Maputo',
      'Matola',
      'Beira',
      'Nampula',
      'Chimoio',
      'Nacala',
      'Quelimane',
      'Tete',
      'Xai-Xai',
      'Gurue',
      'Maxixe',
      'Lichinga',
      'Pemba',
      'Angoche',
      'Inhambane',
      'Cuamba',
      'Montepuez',
      'Chokwe',
      'Chibuto',
      'Ilha de Moçambique',
      'Manica',
      'Mocuba',
      'Namialo',
      'Mocimboa da Praia',
      'Pemba',
      'Pemba',
      'Pemba',
      'Pemba',
      'Pemba',
      'Pemba',
    ],
  },
  {
    code: 'namibie',
    name: 'Namibie',
    flag: '🇳🇦',
    currency: 'NAD',
    phoneCode: '+264',
    cities: [
      'Windhoek',
      'Walvis Bay',
      'Oshakati',
      'Rundu',
      'Katima Mulilo',
      'Otjiwarongo',
      'Keetmanshoop',
      'Mariental',
      'Gobabis',
      'Lüderitz',
      'Swakopmund',
      'Grootfontein',
      'Okahandja',
      'Rehoboth',
      'Otavi',
      'Tsumeb',
      'Gobabis',
      'Gobabis',
      'Gobabis',
      'Gobabis',
      'Gobabis',
      'Gobabis',
      'Gobabis',
      'Gobabis',
      'Gobabis',
      'Gobabis',
      'Gobabis',
      'Gobabis',
      'Gobabis',
      'Gobabis',
    ],
  },
  {
    code: 'rwanda',
    name: 'Rwanda',
    flag: '🇷🇼',
    currency: 'RWF',
    phoneCode: '+250',
    cities: [
      'Kigali',
      'Butare',
      'Gitarama',
      'Ruhengeri',
      'Gisenyi',
      'Byumba',
      'Cyangugu',
      'Kibuye',
      'Kibungo',
      'Nyanza',
      'Gikongoro',
      'Kigali',
      'Kigali',
      'Kigali',
      'Kigali',
      'Kigali',
      'Kigali',
      'Kigali',
      'Kigali',
      'Kigali',
      'Kigali',
      'Kigali',
      'Kigali',
      'Kigali',
      'Kigali',
      'Kigali',
      'Kigali',
      'Kigali',
      'Kigali',
      'Kigali',
      'Kigali',
    ],
  },
  {
    code: 'sao_tome_et_principe',
    name: 'São Tomé-et-Principe',
    flag: '🇸🇹',
    currency: 'STD',
    phoneCode: '+239',
    cities: [
      'São Tomé',
      'Santo António',
      'Neves',
      'Santana',
      'Trindade',
      'Guadalupe',
      'Santo Amaro',
      'Ponta Mina',
      'Bombom',
      'Ribeira Afonso',
      'Santa Catarina',
      'Santa Cruz',
      'Santo António',
      'Santo António',
      'Santo António',
      'Santo António',
      'Santo António',
      'Santo António',
      'Santo António',
      'Santo António',
      'Santo António',
      'Santo António',
      'Santo António',
      'Santo António',
      'Santo António',
      'Santo António',
      'Santo António',
      'Santo António',
      'Santo António',
      'Santo António',
    ],
  },
  {
    code: 'seychelles',
    name: 'Seychelles',
    flag: '🇸🇨',
    currency: 'SCR',
    phoneCode: '+248',
    cities: [
      'Victoria',
      'Anse Boileau',
      'Anse Royale',
      'Beau Vallon',
      'Cascade',
      'Glacis',
      'Grand Anse',
      'La Digue',
      'La Rivière Anglaise',
      'Mont Buxton',
      'Mont Fleuri',
      'Plaisance',
      'Pointe La Rue',
      'Port Glaud',
      'Saint Louis',
      'Takamaka',
      'Victoria',
      'Victoria',
      'Victoria',
      'Victoria',
      'Victoria',
      'Victoria',
      'Victoria',
      'Victoria',
      'Victoria',
      'Victoria',
      'Victoria',
      'Victoria',
      'Victoria',
      'Victoria',
      'Victoria',
    ],
  },
  {
    code: 'somalie',
    name: 'Somalie',
    flag: '🇸🇴',
    currency: 'SOS',
    phoneCode: '+252',
    cities: [
      'Mogadiscio',
      'Hargeisa',
      'Kismayo',
      'Berbera',
      'Merca',
      'Jamaame',
      'Baidoa',
      'Burao',
      'Bosaso',
      'Afgooye',
      'Beledweyne',
      'Galkayo',
      'Garowe',
      'Jowhar',
      'Kismayo',
      'Luuq',
      'Marka',
      'Mogadiscio',
      'Mogadiscio',
      'Mogadiscio',
      'Mogadiscio',
      'Mogadiscio',
      'Mogadiscio',
      'Mogadiscio',
      'Mogadiscio',
      'Mogadiscio',
      'Mogadiscio',
      'Mogadiscio',
      'Mogadiscio',
      'Mogadiscio',
      'Mogadiscio',
    ],
  },
  {
    code: 'soudan',
    name: 'Soudan',
    flag: '🇸🇩',
    currency: 'SDG',
    phoneCode: '+249',
    cities: [
      'Khartoum',
      'Omdurman',
      'Port-Soudan',
      'Kassala',
      'El Obeid',
      'Nyala',
      'Wad Madani',
      'Al Qadarif',
      'Kosti',
      'Juba',
      'Malakal',
      'Wau',
      'Yei',
      'Aweil',
      'Rumbek',
      'Torit',
      'Bentiu',
      'Bor',
      'Kapoeta',
      'Maridi',
      'Yambio',
      'Khartoum',
      'Khartoum',
      'Khartoum',
      'Khartoum',
      'Khartoum',
      'Khartoum',
      'Khartoum',
      'Khartoum',
      'Khartoum',
      'Khartoum',
    ],
  },
  {
    code: 'soudan_du_sud',
    name: 'Soudan du Sud',
    flag: '🇸🇸',
    currency: 'SSP',
    phoneCode: '+211',
    cities: [
      'Juba',
      'Wau',
      'Malakal',
      'Yei',
      'Aweil',
      'Rumbek',
      'Torit',
      'Bentiu',
      'Bor',
      'Kapoeta',
      'Maridi',
      'Yambio',
      'Juba',
      'Juba',
      'Juba',
      'Juba',
      'Juba',
      'Juba',
      'Juba',
      'Juba',
      'Juba',
      'Juba',
      'Juba',
      'Juba',
      'Juba',
      'Juba',
      'Juba',
      'Juba',
      'Juba',
      'Juba',
      'Juba',
    ],
  },
  {
    code: 'tanzanie',
    name: 'Tanzanie',
    flag: '🇹🇿',
    currency: 'TZS',
    phoneCode: '+255',
    cities: [
      'Dar es Salaam',
      'Mwanza',
      'Arusha',
      'Dodoma',
      'Mbeya',
      'Morogoro',
      'Tanga',
      'Kigoma',
      'Musoma',
      'Iringa',
      'Songea',
      'Tabora',
      'Sumbawanga',
      'Bukoba',
      'Singida',
      'Katavi',
      'Shinyanga',
      'Kigoma',
      'Geita',
      'Simiyu',
      'Njombe',
      'Songwe',
      'Dar es Salaam',
      'Dar es Salaam',
      'Dar es Salaam',
      'Dar es Salaam',
      'Dar es Salaam',
      'Dar es Salaam',
      'Dar es Salaam',
      'Dar es Salaam',
      'Dar es Salaam',
    ],
  },
  {
    code: 'ouganda',
    name: 'Ouganda',
    flag: '🇺🇬',
    currency: 'UGX',
    phoneCode: '+256',
    cities: [
      'Kampala',
      'Gulu',
      'Lira',
      'Mbarara',
      'Jinja',
      'Bwizibwera',
      'Mbale',
      'Mukono',
      'Kasese',
      'Masaka',
      'Arua',
      'Entebbe',
      'Tororo',
      'Kabale',
      'Soroti',
      'Kisoro',
      'Bushenyi',
      'Iganga',
      'Bugiri',
      'Kotido',
      'Kampala',
      'Kampala',
      'Kampala',
      'Kampala',
      'Kampala',
      'Kampala',
      'Kampala',
      'Kampala',
      'Kampala',
      'Kampala',
      'Kampala',
    ],
  },
];
